version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:15.4-alpine3.18
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}